### ISSUE TITLE
Introduce variable

### ISSUE THREAD

**Issue by oSumAtrIX** [BlauFx/RhythmBox#20]
Accessing an item in an array multiple times is a heavy operation and should be saved to a local variable instead
https://github.com/BlauFx/RhythmBox/blob/58c268e8e96150e30f3c969d1e942e22a3008dea/RhythmBox.Window/Mode/Standard/Maps/Map.cs#L97

**Comment by BlauFx** [comment]
Yeah, I agree with you.

**Comment by BlauFx** [comment]
Fixed in https://github.com/BlauFx/RhythmBox/commit/9f26435bbb53a656f8a29cc81018fb49bfd18284
